#!/bin/bash

# Script de Demonstração das Novas Funcionalidades
# Sistema Escolar - Médias, Histórico e Persistência

echo "════════════════════════════════════════════════════════════"
echo "  TESTE DAS NOVAS FUNCIONALIDADES"
echo "════════════════════════════════════════════════════════════"
echo ""
echo "Este script demonstra:"
echo "  ✓ Cálculo de médias por disciplina"
echo "  ✓ Histórico acadêmico completo do aluno"
echo "  ✓ Persistência em banco de dados (CSV)"
echo ""
echo "INSTRUÇÕES PARA TESTE MANUAL:"
echo ""
echo "1. TESTE DE MÉDIAS E HISTÓRICO:"
echo "   - Execute: ./app"
echo "   - Entre como Coordenador (1, ID 1)"
echo "   - Crie disciplina (código 1, nome Programação, carga 60)"
echo "   - Abra turma (código 100, disciplina 1, professor 10, nome 2024.1)"
echo "   - Matricule alunos 100 e 101 na turma 100"
echo ""
echo "   - Entre como Professor (2, ID 10)"
echo "   - Crie avaliação (turma 100, código 1, Prova 1)"
echo "   - Crie avaliação (turma 100, código 2, Prova 2)"
echo "   - Lance notas:"
echo "     * Aluno 100, Prova 1: 8.5"
echo "     * Aluno 100, Prova 2: 7.0"
echo "     * Aluno 101, Prova 1: 9.0"
echo "     * Aluno 101, Prova 2: 6.0"
echo ""
echo "   - Entre como Aluno (3, ID 100)"
echo "   - Opção 2: Ver Histórico Completo"
echo "   - Você verá:"
echo "     * Todas as disciplinas cursadas"
echo "     * Todas as notas lançadas"
echo "     * Média calculada: (8.5 + 7.0) / 2 = 7.75"
echo "     * Status: Aprovado (média >= 7.0)"
echo "     * Resumo geral com estatísticas"
echo ""
echo "2. TESTE DE PERSISTÊNCIA:"
echo "   - Após criar dados acima, escolha opção 9 (Salvar Dados Agora)"
echo "   - Ou simplesmente saia (opção 0) - salvará automaticamente"
echo "   - Verifique os arquivos criados:"
echo "     * data/alunos.csv"
echo "     * data/professores.csv"
echo "     * data/disciplinas.csv"
echo "     * data/turmas.csv"
echo ""
echo "   - Execute ./app novamente"
echo "   - Os dados serão carregados automaticamente!"
echo ""
echo "3. CRITÉRIOS DE APROVAÇÃO:"
echo "   - Média >= 7.0: Aprovado"
echo "   - Média >= 5.0 e < 7.0: Recuperação"
echo "   - Média < 5.0: Reprovado"
echo ""
echo "════════════════════════════════════════════════════════════"
echo ""
read -p "Pressione ENTER para iniciar o programa..."

./app
